global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'nginx'
    static_configs:
      - targets: ['172.18.0.4:9100']
  - job_name: 'rust_api'
    static_configs:
      - targets: ['172.18.0.2:9100']
  - job_name: 'node_api'
    static_configs:
      - targets: ['172.18.0.3:9100']
